# Generates the flash-resident BLE GATT service-UUID name table from the committed
# Bluetooth SIG snapshot at data/ble/service_uuids.csv.
#
# Output: src/activities/util/BleServiceUuids.h  (committed; compiled into flash).
#
# The 16-bit GATT service list is tiny (~75 entries, ~2 KB), so unlike the company
# database it stays in flash -- no SD file needed. ra::bleServiceName() looks it up.
# Re-run this script if data/ble/service_uuids.csv is updated from upstream.

import os

ROOT = os.getcwd()
SRC = os.path.join(ROOT, "data", "ble", "service_uuids.csv")
OUT = os.path.join(ROOT, "src", "activities", "util", "BleServiceUuids.h")


def main():
    rows = []  # (uuid_int, name)
    with open(SRC, encoding="ascii") as f:
        for line in f:
            line = line.rstrip("\n")
            if not line or line.startswith("#"):
                continue
            hex4, _, name = line.partition(",")
            hex4 = hex4.strip()
            name = name.strip().replace('"', "'")
            if not hex4 or not name:
                continue
            try:
                uuid = int(hex4, 16)
            except ValueError:
                continue
            rows.append((uuid, name))

    rows.sort(key=lambda r: r[0])

    with open(OUT, "w", encoding="ascii") as out:
        out.write("#pragma once\n\n")
        out.write("#include <cstdint>\n\n")
        out.write("// AUTO-GENERATED by scripts/gen_ble_services.py from data/ble/service_uuids.csv.\n")
        out.write("// Bluetooth SIG assigned 16-bit GATT service UUIDs, sorted by uuid (binary search).\n")
        out.write("// Small enough (~%d entries) to stay in flash; do not edit by hand.\n\n" % len(rows))
        out.write("namespace ra {\n\n")
        out.write("struct BleServiceName {\n  uint16_t uuid;\n  const char* name;\n};\n\n")
        out.write("inline constexpr BleServiceName BLE_SERVICE_NAMES[] = {\n")
        for uuid, name in rows:
            out.write('    {0x%04X, "%s"},\n' % (uuid, name))
        out.write("};\n\n")
        out.write("inline constexpr int BLE_SERVICE_NAME_COUNT =\n")
        out.write("    static_cast<int>(sizeof(BLE_SERVICE_NAMES) / sizeof(BLE_SERVICE_NAMES[0]));\n\n")
        out.write("}  // namespace ra\n")

    print("Wrote %s: %d services" % (OUT, len(rows)))


if __name__ == "__main__":
    main()
